### ISSUE TITLE
Refreshing pages

### ISSUE THREAD

**Issue by HishamMubarak** [A2Z-hq/a2z-frontend#31]
The front-end site works fine in the homepage and navigating to other pages.
But while refreshing a page or entering into a sub-domain directly, it shows a 404 error.
I am not sure if this is a problem with React  or React Navigation or Github pages.

**Comment by Contrevien** [comment]
This is a problem that arose due to my carelessness with react-router package. I have however tried to resolve it in the current PR. Check the deployed version of currently active PR.

**Comment by HishamMubarak** [comment]
Seems to be fixed. Closing the issue.

**Comment by Contrevien** [comment]
@HishamMubarak This problem will persist as Github pages on serves static websites, while the router that I have used is built for dynamic server, however I have added a tweak to make it work on Github pages somehow but the problem of refreshing pages will not be solved for Github pages. But since our app runs perfectly on ZIET Now (which serves dynamic wesbites), our app shall face no problem on a real server as well.
