### ISSUE TITLE
How about React?

### ISSUE THREAD

**Issue by HishamMubarak** [A2Z-hq/a2z-frontend#6]
Since we need login features, auth and more , isn't it better if we used react  than VanillaJs? Let me know what you think.

**Comment by Contrevien** [comment]
SInce the project was Open Source, I wanted to keep it as minimal as possible making it easier for even young developers to contribute.

But now that we are involving OAuth and API data exchange dynamically, I think it's best to switch over to React.
Will you be contributing to Front-end if I switched the project to React? If yes, then in a few hours, I will publish a side branch with React. How does that sound?

**Comment by HishamMubarak** [comment]
> @HishamMubarak SInce the project was Open Source, I wanted to keep it as minimal as possible making it easier for even young developers to contribute.
> 
> But now that we are involving OAuth and API data exchange dynamically, I think it's best to switch over to React.
> Will you be contributing to Front-end if I switched the project to React?
> 
> @miteshree Are you OK with React as the choice for frontend?

I will be contributing to front-end if its React or VanillaJs, let me know which one you chose to move forward with. I recommended react because, like you said, we are making use of Auth, API exchanges, it'll be better and easier to work with React,

**Comment by Contrevien** [comment]
This issue will be decided by the conslusion of #7
